import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import ReactQueryProvider from "../components/ReactQueryProvider";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${geistSans.variable} ${geistMono.variable} bg-neutral-900 text-neutral-100 antialiased flex h-screen`}>
        <Sidebar />
        <ReactQueryProvider>
          <main className="flex-1 bg-neutral-900 text-neutral-100">{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
